format_version: 4
common:
  repo_deploy_tasks: &repo_deploy_tasks
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks generate_certs repo
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks upload_certs repo
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks tf_plan_repo create
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks tf_apply

  test_harness_deploy_tasks: &test_harness_deploy_tasks
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks generate_certs test_harness
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks upload_certs test_harness
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks tf_plan_test_harness create
    - exec:
        command: /bin/bash
        working_directory: prm-mhs-infra
        arguments:
          - -c
          - ./tasks tf_apply

pipelines:
  "prm-mhs-infra-opentest":
    group: mhs
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        destination: prm-mhs-infra
      integration_adaptors:
        git: https://github.com/nhsconnect/prm-deductions-integration-adaptors.git
        branch: deductions
        destination: integration-adaptors
      docker:
        pipeline: mhs-docker-images
        stage: build
      docker_dns_images:
        pipeline: mhs-dns-images
        stage: test
      deductions_infra:
        pipeline: prm-deductions-infra
        stage: check_dev
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages:
      - deploy:
          clean_workspace: true
          jobs:
            repo:
              resources:
                - docker
              tasks: *repo_deploy_tasks
            test_harness:
              resources:
                - docker
              tasks: *test_harness_deploy_tasks

  "prm-mhs-infra-ptl-integration":
    group: mhs
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        destination: prm-mhs-infra
      integration_adaptors:
        git: https://github.com/nhsconnect/prm-deductions-integration-adaptors.git
        branch: deductions
        destination: integration-adaptors
      system_integration:
        git: https://github.com/nhsconnect/prm-deductions-mhs-system-integration.git
        destination: system-integration
      docker:
        pipeline: mhs-docker-images
        stage: build
      docker_dns_images:
        pipeline: mhs-dns-images
        stage: test
      dev_env:
        pipeline: prm-mhs-infra-opentest
        stage: deploy
    environment_variables:
      NHS_ENVIRONMENT: test
    stages:
      - deploy:
          clean_workspace: true
          jobs:
            deploy:
              resources:
                - docker
              tasks:
                - *repo_deploy_tasks
                - exec:
                    command: /bin/bash
                    working_directory: prm-mhs-infra
                    arguments:
                      - -c
                      - ./tasks nlb_ips create